/**
 * Auto-generated TypeScript types from Pydantic BrandingConfig.
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-config-types.py
 * Generated: 2026-01-19T09:12:40.092793Z
 */

export interface BrandingConfig {
  app_name: string;
  app_description?: string | null;
  bot_name: string;
  logo_url?: string | null;
  primary_color?: string | null;
}
