#!/usr/bin/env python3
"""
Generate TypeScript types from Pydantic config schema.

This script reads the BrandingConfig model from core/config.py and generates
corresponding TypeScript types for frontend consumption.

Usage:
    python scripts/generate-config-types.py
"""
import sys
from pathlib import Path
from datetime import datetime

# Add backend to path
backend_path = Path(__file__).parent.parent / '02_backend'
sys.path.insert(0, str(backend_path))

from core.config import BrandingConfig
from pydantic.fields import FieldInfo


def pydantic_type_to_typescript(field_type: type, field_info: FieldInfo) -> str:
    """Convert Pydantic field type to TypeScript type.

    Args:
        field_type: Python type annotation.
        field_info: Pydantic field information.

    Returns:
        TypeScript type string.
    """
    # Handle Optional types
    is_optional = field_info.is_required() == False

    # Get the base type
    type_str = str(field_type)

    if 'str' in type_str:
        ts_type = 'string'
    elif 'int' in type_str:
        ts_type = 'number'
    elif 'float' in type_str:
        ts_type = 'number'
    elif 'bool' in type_str:
        ts_type = 'boolean'
    else:
        ts_type = 'any'

    # Add null for optional fields
    if is_optional or 'None' in type_str or 'Optional' in type_str:
        ts_type = f'{ts_type} | null'

    return ts_type


def generate_branding_config_types() -> str:
    """Generate TypeScript types from BrandingConfig.

    Returns:
        TypeScript type definition as string.
    """
    lines = [
        '/**',
        ' * Auto-generated TypeScript types from Pydantic BrandingConfig.',
        ' * DO NOT EDIT MANUALLY - Generated by scripts/generate-config-types.py',
        f' * Generated: {datetime.utcnow().isoformat()}Z',
        ' */',
        '',
        'export interface BrandingConfig {',
    ]

    # Get model fields
    for field_name, field_info in BrandingConfig.model_fields.items():
        # Get field type
        field_type = field_info.annotation
        ts_type = pydantic_type_to_typescript(field_type, field_info)

        # Add JSDoc comment with field description
        if field_info.description:
            lines.append(f'  /** {field_info.description} */')

        # Add field
        optional_marker = '?' if not field_info.is_required() else ''
        lines.append(f'  {field_name}{optional_marker}: {ts_type};')

    lines.append('}')
    lines.append('')

    return '\n'.join(lines)


def main():
    """Generate TypeScript config types."""
    # Generate types
    typescript_code = generate_branding_config_types()

    # Write to frontend types directory
    frontend_types_dir = Path(__file__).parent.parent / '03_frontend' / 'src' / 'types'
    frontend_types_dir.mkdir(parents=True, exist_ok=True)

    output_file = frontend_types_dir / 'config.ts'
    output_file.write_text(typescript_code)

    print(f'✓ Generated TypeScript types: {output_file}')
    print(f'✓ Generated {len(BrandingConfig.model_fields)} fields')


if __name__ == '__main__':
    main()
